/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nhansen' at '10/14/16 8:47 PM' with Gradle 2.14.1
 *
 * @author nhansen, @date 10/14/16 8:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
